### ISSUE TITLE
Angular2 AOT + Rollup 

### ISSUE THREAD

**Issue by morscad** [salemdar/angular2-cookies#34]
I used this project:
https://github.com/johnpapa/angular2-go
and implemented angular2-cookie as follows:

`import { NgModule } from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule, XHRBackend } from '@angular/http';
import { CookieService } from 'angular2-cookie/services/cookies.service';

import { AppComponent }   from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  declarations: [AppComponent],
  providers: [CharacterService, CookieService],
  bootstrap: [AppComponent],
})
export class AppModule { }`

and then

`import

 { Component } from '@angular/core';

import { CharacterService } from './character.service';
import {CookieService} from 'angular2-cookie/core';

@Component({
  selector: 'my-app'
})
export class AppComponent { 
	constructor(private _cookieService:CookieService)
	{
		console.log(this._cookieService.get("omar"));
	}

}`

and then ran `npm run start-aot`

and I got this message

`'CookieService' is not exported by node_modules/angular2-cookie/core.js (imported by app/app.component.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'CookieService' is not exported by node_modules/angular2-cookie/core.js (imported by app/app.component.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at Module.trace (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/Module.js:362:30)
    at ModuleScope.findDeclaration (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/scopes/ModuleScope.js:47:22)
    at Scope.findDeclaration (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/scopes/Scope.js:90:39)
    at Identifier.bind (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/nodes/Identifier.js:7:29)
    at /Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:6:34
    at Node.eachChild (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:21:5)
    at Node.bind (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:6:8)
    at /Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:6:34
    at ObjectExpression.eachChild (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:18:20)
    at ObjectExpression.bind (/Users/morscad/Desktop/angular2-go-master 2/node_modules/rollup/src/ast/Node.js:6:8)`

**Comment by prabhu43** [comment]
@morscad I too faced this issue. And then resolved it by using namedExports in rollup config.
```
commonjs({
            include: 'node_modules/**/**',
            namedExports: {
                'node_modules/angular2-cookie/core.js': [ 'CookieService' ]
            }
        })
```

**Comment by dineshba** [comment]
try with `import { CookieService } from 'angular2-cookie/core';`
